In [ ]:
# Tensors:
# tensors are way to represent multidimensional data

In [2]:
import torch

torch.__version__

'2.6.0'

In [46]:
# scalar - 0 dimension
scalar = torch.tensor(10)

scalar.ndim, scalar.dtype, scalar.shape

(0, torch.int64, torch.Size([]))

In [48]:
type(scalar.item())

int

In [55]:
# vector -  1 dimensiom
vector = torch.tensor([10, 2, 3])

vector.ndim, vector.dtype, vector.shape


(1, torch.int64, torch.Size([3]))

In [56]:
vector

tensor([10,  2,  3])

In [58]:
# matrix
MATRIX = torch.tensor([[1,2,3], 
                       [4,5,6]])

MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [61]:
MATRIX.ndim, MATRIX.dtype, MATRIX.shape

(2, torch.int64, torch.Size([2, 3]))

In [62]:
MATRIX[0]

tensor([1, 2, 3])

In [63]:
# TENSOR
TENSOR =  torch.tensor([[[1,2,3], 
                         [4,5,6], 
                         [7,8,9]]])

In [64]:
TENSOR


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [98]:
TENSOR[:, :, 0]

tensor([[1, 4, 7]])

In [99]:
TENSOR[:, 0]

tensor([[1, 2, 3]])

In [122]:
t = torch.arange(1,13).reshape(1,2,3,2)

t

tensor([[[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],

         [[ 7,  8],
          [ 9, 10],
          [11, 12]]]])

In [123]:
t.shape

torch.Size([1, 2, 3, 2])

In [141]:
t[0,1,:,0]

tensor([ 7,  9, 11])