In [30]:

import torch

In [31]:
# random tensors - neural network use this 
torch.manual_seed(42)
n  =torch.rand(2,3)
n

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [32]:
n.shape , n.dtype

(torch.Size([2, 3]), torch.float32)

In [33]:
n[1][1].item()

0.3904482126235962

In [36]:
# zeros and one

ones = torch.zeros(2,3)
zero = torch.zeros(3,4)
ones , zero

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]))

In [38]:
ones + 10

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [39]:
ones = torch.ones(2,3)
zero = torch.ones(3,4)
ones , zero

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))