In [1]:
import torch

In [2]:
torch.__version__

'2.6.0'

In [6]:
# range tensors

n = torch.arange(1,11, 2)
n

tensor([1, 3, 5, 7, 9])

In [7]:
# tensors like

torch.zeros_like(n)


tensor([0, 0, 0, 0, 0])

In [12]:
torch.ones_like(torch.tensor([[1,2,3],
                              [4,5,6]]))

tensor([[1, 1, 1],
        [1, 1, 1]])