In [10]:
import torch

In [11]:
# Add, mul(element wiae mult),div and matrix multiplication

one = torch.tensor([1,2,3,4])

one

tensor([1, 2, 3, 4])

In [12]:
one + 10

tensor([11, 12, 13, 14])

In [13]:
one *10

tensor([10, 20, 30, 40])

In [14]:
one/10

tensor([0.1000, 0.2000, 0.3000, 0.4000])

In [15]:
one@one

tensor(30)

In [16]:
one.matmul(one)

tensor(30)

In [18]:
one

tensor([1, 2, 3, 4])

In [20]:
%%time



CPU times: user 1 μs, sys: 0 ns, total: 1 μs
Wall time: 3.1 μs


In [28]:
one = torch.rand(2,3)
one

two = torch.rand(3,7)

In [31]:
one.matmul(two).shape

torch.Size([2, 7])

In [30]:
one.shape , two.shape

(torch.Size([2, 3]), torch.Size([3, 7]))

In [33]:
tensor_A = torch.tensor([[1,2,3],
                         [4,5,6],
                         [7,8,9]])

tensor_B = torch.tensor([[2,4,6],
                         [6,8,0],
                        [3,2,1]])

In [34]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 3]), torch.Size([3, 3]))

In [37]:
tensor_A.matmul(tensor_B)

tensor([[ 23,  26,   9],
        [ 56,  68,  30],
        [ 89, 110,  51]])

In [38]:


tensor_A

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [39]:
tensor_A.T

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [46]:
a = torch.rand(1,2,3)
b = torch.rand(2,3,1)
a.shape, b.shape

(torch.Size([1, 2, 3]), torch.Size([2, 3, 1]))

In [47]:
a.matmul(b)

tensor([[[1.1925],
         [1.5542]],

        [[0.9826],
         [1.3704]]])