In [1]:
import torch

torch.__version__

'2.6.0'

In [11]:
one = torch.arange(1,10)

one

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
two  = one.reshape(3,3)

two

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
one

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
three = one.view(3,3)

three

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [15]:
one, three

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

In [18]:
three[0][0] = 100

In [19]:
three

tensor([[100,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]])

In [20]:
one

tensor([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [27]:
# stack tensors

one = torch.arange(1,4)

one

tensor([1, 2, 3])

In [31]:
torch.stack([one], dim=1)

tensor([[1],
        [2],
        [3]])

In [32]:
one

tensor([1, 2, 3])

In [38]:
new = one.reshape(3,1)

new


tensor([[1],
        [2],
        [3]])

In [45]:
torch.stack([new], dim=1)

tensor([[[1]],

        [[2]],

        [[3]]])

In [48]:
one = torch.arange(1,4)

one , one.shape

(tensor([1, 2, 3]), torch.Size([3]))

In [52]:
new = torch.stack([one, one])

new, new.shape

(tensor([[1, 2, 3],
         [1, 2, 3]]),
 torch.Size([2, 3]))

In [70]:
new.shape

torch.Size([2, 3])

In [66]:
one  = one.unsqueeze(dim=0).unsqueeze(dim=0).squeeze()

one, one.shape

(tensor([1, 2, 3]), torch.Size([3]))

In [76]:
one, one.shape, one.ndim

(tensor([1, 2, 3]), torch.Size([3]), 1)

In [77]:
one.permute(0)

tensor([1, 2, 3])

In [80]:
one = torch.arange(1,10).reshape(3,3)
one, one.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [82]:
one.permute(1,0)

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])