In [1]:
import torch

In [5]:
x = torch.arange(1,10).reshape(1,3,3)

x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [6]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
x[0,0] , x[0][0]  # both are same

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [11]:
x[0][0][0], x[0,0,0]

(tensor(1), tensor(1))

In [13]:
x[:,:, 0]

tensor([[1, 4, 7]])

In [16]:
x[:, 1,1]

tensor([5])

In [18]:
x,  x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [21]:
x[0][1][1]

tensor(5)

In [24]:
x[:,1,1]

tensor([5])

In [38]:
x[:,0,0]

tensor([1])