In [5]:
import torch
import numpy as np


data = np.array([10])
data


array([10])

In [8]:
# convert numpy data into pytorch tensorts

torch_tensor = torch.from_numpy(data)

torch_tensor

tensor([10])

In [9]:
# convert pytorch to numpy arraay

torch_tensor.numpy()

array([10])

In [12]:
# default datatype of numpy float64

one_numpy = np.arange(1.0,10.0)
one_numpy, one_numpy.dtype

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]), dtype('float64'))

In [17]:
torch.from_numpy(one_numpy).type(torch.float32)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])