In [1]:
import torch

In [6]:
# reproducibility check

num = torch.rand(1,10)
num

tensor([[0.7820, 0.4015, 0.4303, 0.4285, 0.7762, 0.3066, 0.7549, 0.5245, 0.0238,
         0.6983]])

In [16]:
torch.manual_seed(42)

one = torch.rand(1,11)
torch.manual_seed(42)

two = torch.rand(1,11)

one, two

(tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
          0.1332, 0.9346]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
          0.1332, 0.9346]]))

In [17]:
one == two

tensor([[True, True, True, True, True, True, True, True, True, True, True]])