In [1]:
import torch

In [26]:
# scalar ? 
scalar = torch.tensor(10)

scalar, scalar.shape ,scalar.dtype

(tensor(10), torch.Size([]), torch.int64)

In [4]:
scalar.ndim

0

In [28]:
vector = torch.tensor([1,2,3])

vector , vector.ndim , vector.shape , vector.dtype

(tensor([1, 2, 3]), 1, torch.Size([3]), torch.int64)

In [8]:
n = torch.tensor([1,2,3])

n.ndim


1

In [9]:
MATRIX = torch.tensor([[1,2,3],
                       [4,5,6]])

In [11]:
MATRIX.ndim

2

In [14]:
a = torch.tensor(10) # 0 th dimesion no shape

a.shape, a.ndim

(torch.Size([]), 0)

In [16]:
b = torch.tensor([[1,2,3]])
b.shape

# Row * column ==>  1, 3

torch.Size([1, 3])

In [18]:
c = torch.tensor([1,2,3])
c.ndim , c.shape

(1, torch.Size([3]))

In [21]:
c = torch.tensor([[1,2,3],
                  [4,5,6]])

c.ndim , c.shape

(2, torch.Size([2, 3]))

In [24]:
d = torch.tensor([[1],
                  [2],
                  [3]])

d.ndim, d.shape

(2, torch.Size([3, 1]))

In [25]:
# create n dim tensor - 2,5,3


n =  torch.rand(size=(2,5,3))
n

tensor([[[0.4885, 0.0117, 0.1000],
         [0.3174, 0.9389, 0.5384],
         [0.7139, 0.6714, 0.8271],
         [0.6881, 0.7120, 0.3797],
         [0.4688, 0.8444, 0.5177]],

        [[0.9157, 0.5065, 0.4092],
         [0.9856, 0.1244, 0.5979],
         [0.5190, 0.6526, 0.6639],
         [0.2458, 0.9159, 0.8213],
         [0.5555, 0.9894, 0.2582]]])

In [30]:
a = torch.tensor(10, dtype=torch.float)
a.dtype

torch.float32

In [32]:
a = a.type(torch.int64)

a.dtype

torch.int64

In [33]:
a

tensor(10)

In [34]:
a.device

device(type='cpu')

In [37]:
## Build an LLM
## LLM - Large lang model
##  LLM --  chatgpt(openai -  closed), gemini(gooogle -closed), claude(weak,  resaon), grok(twitter -elon musk, closed), deepseek(chinese-open) ,Lllam(meta -open)

# model size -- parameter 1B, 10M, 3M


!nvidia-smi

zsh:1: command not found: nvidia-smi


In [5]:
# zero tensor
import torch

a = torch.zeros(size=(1,5,2,3))

a.ndim, a.shape

(4, torch.Size([1, 5, 2, 3]))

In [13]:
b = torch.ones(size=(2,3))
b.dtype , b.shape , b.ndim

(torch.float32, torch.Size([2, 3]), 2)

In [15]:
# range tensor

a = torch.arange(1,10, 2)

a ,  a.ndim, a.shape

(tensor([1, 3, 5, 7, 9]), 1, torch.Size([5]))

In [16]:
# like tensor

a = torch.rand(size=(2,3))

a


tensor([[0.6611, 0.2959, 0.2286],
        [0.1481, 0.0686, 0.5001]])

In [21]:
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [22]:
# CPU  vs GPU
# CUDA is a toolkit to check if nvidia gpu is avable or not

torch.cuda.is_available()

False

In [ ]:
# train a model
# model - how to predict, if a image is pizza or not
# supervised(label data provided for training) vs unsupervised (no label data, )
# supervised model ---> food vision model (label data)

#Training: 
        #Input data - label data (X , y)
# What ? 
# build a model to classify image - pytorch

# Train rule : 




    

# First
# Preprocing : #Input data 
# convert the raw input into feature tensors/ feature vector
# convert


# Training a model: 
# foward pass -->  calc the loss --> backpropagtion ---> optimse the gradient


In [23]:
float_32_tensor = torch.tensor([3, 6, 9],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device


(torch.Size([3]), torch.int64, device(type='cpu'))

In [25]:
# manipilating tensor

# add

a = torch.tensor([1,2,3])

a * 100

tensor([100, 200, 300])

In [26]:
torch.multiply(a,100)

tensor([100, 200, 300])

In [28]:
a = torch.tensor([1,2,3])
b = torch.tensor([2,4,6])

a*b


tensor([ 2,  8, 18])

In [31]:
# matrix multiplication
a = torch.tensor([1,2,3])
b = torch.tensor([2,4,6])

a.ndim , a.shape

(1, torch.Size([3]))

In [32]:
a.matmul(b)        # 3 & 3

tensor(28)

In [33]:
torch.matmul(a,b)

tensor(28)

In [34]:
a@b

tensor(28)

In [43]:
a = torch.tensor([[2,4],
                  [6,8]])

b= torch.tensor([[2,4, 6],
                  [6,8 ,10]])

In [44]:
a.ndim , a.shape ,  b.ndim, b.shape     # 2,2  and 2,3

(2, torch.Size([2, 2]), 2, torch.Size([2, 3]))

In [45]:
a@b

tensor([[ 28,  40,  52],
        [ 60,  88, 116]])

In [ ]:
un_trained_model == 

1.png ---> pizza
2.png ---> pizza

# trained with above data

trained_model---> it can identify pizza


3.png ---> elephant

trained_model(2.png) --->


