In [2]:
# import tensorflow
import tensorflow as tf


tf.__version__


'2.19.0'

In [13]:
# create a scalar
scalar = tf.constant([[10]])

scalar

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[10]], dtype=int32)>

In [17]:
scalar.ndim , scalar.shape, scalar.dtype 


(2, TensorShape([1, 1]), tf.int32, array([[10]], dtype=int32))

In [19]:
scalar.numpy()

array([[10]], dtype=int32)

In [20]:
matric = tf.constant([[10,7],
                      [3,8]]
                    )
matric

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  8]], dtype=int32)>

In [21]:
matric.shape


TensorShape([2, 2])

In [22]:
matric[0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [28]:
one = tf.constant([[9.0, 10.0]])

In [29]:
one

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[ 9., 10.]], dtype=float32)>